// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyjktbmvwbojvzknahiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55amt0Ym12d2JvanZ6a25haGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0MDUwNTQsImV4cCI6MjA4Njk4MTA1NH0.VsfI7XReXEkhEhF2yUppv50P5n8AkerzkZQwEPwZXXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});